# Generated by Django 5.1.1 on 2024-09-08 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Gamers',
        ),
    ]
