# Generated by Django 5.1.1 on 2024-09-08 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_rename_users_gamers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamers',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='gamers',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='gamers',
            name='is_superuser',
        ),
    ]
